### ISSUE TITLE
extra "01"

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#163]
from user **Nukeboyt**
> "....See pictures 4 and 5 in the album: http://imgur.com/a/DsF9G?gallery. Some numbers appear to
> have extra "01" at the beginning. Example: The Periapsis with Minimus is T-2h 37m 48s (picture 4). 
> But on the ORBIT / RENDEZVOUS DATA screen, it shows the PeT: 01:02:38:00.1s . Would not this 
> mean 1day, 2h, 38m, 00.1s (picture 5)? So the "01" is coming from somewhere. ...."

my MFD page deinition
```ApT:    {0:KDT-dd:hh:mm:ss.f}s ... $&$ TIMETOAPSECS```
```PeT:    {0:KDT-dd:hh:mm:ss.f}s ... $&$ TIMETOPESECS```
```OP:     {0:KDT-dd:hh:mm:ss.f}s ... $&$ ORBPERIODSECS```
```AnT:    {0:KDT-dd:hh:mm:ss.f}s ... $&$ TIMETOANEQUATORIAL```
```DnT:    {0:KDT-dd:hh:mm:ss.f}s ... $&$ TIMETODNEQUATORIAL```

**Comment by MOARdV** [comment]
Assuming Nukeboyt is using the more recent releases of RPM (the ones I've done during 0.90), this is most likely a side-effect of the fix I made for the calendar being a day off.  In issue #156 there was a problem with MET, since the calendar counts from Day 1 instead of Day 0.  The fix should be updating the MFD to use `MET` instead of `KDT`.

**Comment by Alexustas** [comment]
yup, just changed KDT to MET and all become fine. Many thanks, problem solved.
