### ISSUE TITLE
Looping prop animation that consumes resources while active?

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#197]
With the current prop modules, it is possible to have an animated prop that:
 - runs constantly
 - consumes resources while active
 - reverts to an "off" state when said resource is consumed?

Use case:
I want to make a decorative set of [Blinkenlights](http://en.wikipedia.org/wiki/Blinkenlights) on a FusTek prop, which represents whether each of the eight drawers in a rack are receiving power/data/temperature control. I can devise an animation of various LEDs blinking in random sequences, but this animation should run constantly without user interaction, and the LEDs should turn off if the vessel has no ElectricCharge left.

**Comment by MOARdV** [comment]
Right now there aren't any modules that do all of that - I can find two modules who do one of those actions.  JSIVariableAnimator can be set up to activate when there's electric charge using a threshold function, and it can run an animation, but it doesn't currently consume resources, nor does it support looping animation.  However, both of those requirements should be fairly easy to add.

**Comment by MOARdV** [comment]
Are you okay with it snapping to the "off" state, or does it need to finish playing its animation to transition to it?  If it's the former, I think I may be close to having something workable.

**Comment by sumghai** [comment]
Interrupting the animation and snapping to the off state immediately is perfectly fine (and in fact, desirable for my use case :) )

**Comment by MOARdV** [comment]
Okay, it looks like this is in and working.  I should have v0.19.3 released with this functionality some time today.

**Comment by sumghai** [comment]
Coolio, I'll be sure to try it out this weekend.

Thanks again! :)

**Comment by sumghai** [comment]
@MOARdV: 

I've pushed to sumghai/FusTek_StationParts@3df385ff3b178797118b63426f52cdbeb241f7b4 my attempt at implementing this new feature - please let me know if I've done the following correctly:

```
MODULE
{	
		name = JSIVariableAnimator
		animationName = RackLedBlinkerLoop
		loopingAnimation = true
		threshold = 0.0,1.0
		resourceAmount = 0.002
}
```

(I'm assuming that setting the threshold value like that should make the animation run as long as there is _any_ amount of ElectricCharge present, unless I'm missing something else more obvious)

**Comment by MOARdV** [comment]
It needs to have `variableName = SYSR_ELECTRICCHARGE` and `scale = 0,1` (the upper end doen't really matter, but I was using a small value).  I'll have to wait until I am back home to test it and confirm, since I am traveling the first half of this week.

**Comment by sumghai** [comment]
Aha, I knew I was missing something!

Thanks for the pointers - I'll get one of my beta testers to check things out, so don't worry :)

**Comment by sumghai** [comment]
Okay, so I've added `variableName = SYSR_ELECTRICCHARGE` and `scale = 0,1` as advised, but my beta testers are reporting that they aren't seeing the animations working on the internal racks.

[Latest version of FusTek repo] (https://github.com/sumghai/FusTek_StationParts/archive/master.zip)

Notes on how the animations were originally configured in Unity:
 - By default, the blinkenlights are off
 - The blinkenlights are meant to be on from the first to the last frame of the animations (the power LEDs are on constantly, while the data and temperature LEDs blink)

**Comment by MOARdV** [comment]
Is the animation intended to be a looping animation, or a one-shot?

**Comment by MOARdV** [comment]
I'm looking at this currently - one issue I see: there is no animationSpeed defined for the prop.  For whatever reason, that value defaults to '0' if missing.  However, even with me adding a speed of 1.0, I don't see anything happening (I assume the props I'm looking at are "above" the crew in the hab module, where there appear to be a row of switches with lights).  Is there a particular speed I should try?

**Comment by sumghai** [comment]
The speed shouldn't matter, AFAIK.

Yeah, the blinkenlights are the row of switches with lights, although they actually present at the bottom edge of all the rack panels as well as the top of the module.

**Comment by MOARdV** [comment]
Okay.  There are layers of problems with this...

1) As previously noted, animationSpeed needs to be defined in the config.  Even with that, the lights didn't work because

2) The algorithm for determining if there were enough resources to activate the animation was so incredibly wrong that it couldn't work.  But fixing that still didn't work because

3) For some reason, I have to explicitly tell the animation to play (differently that we had to do for other animations).

Now I've got the blinkenlighten playing correctly, but ... the animation stops when I stop them and some of the lights are still visible.  I set the animation to a normalized time of 0 (rewinding it, nominally), and the animation stops, but some lights are still visible.  I'm not sure what I need to do to make them all disappear - the pattern is consistent each time it's stopped, so I assume that's keyframe 0 of the animation, but I'm not sure why it's not visible before the animation starts.  Most likely it's Unity stuff that I don't know.

By the way - one other thing in the part config will need to change.  Since the electric charge threshold is set to (0.0, 1.0), the threshold test will always pass, so the lights never turn off.  To have them turn off when power is out, you'll want to raise the lower threshold above 0 (maybe to 0.5). With the scale set to (0.0, 1.0), a lower threshold of 0.5 will mean the lights go out when there is < 0.5 total charge in the craft.

**Comment by sumghai** [comment]
I recently downgraded to Unity 4.2.2 in order to do the emissive animations for the LEDs, so that may have something to do with the unusual behaviour we're seeing. I'll probably toss up a screenshot or GIF of the animation playing in the Unity editor.

Is the threshold scaled based on the total amount ElectricCharge available in the vessel (i.e. 0.5 means 50%), or absolute values (i.e. literally 0.5 units) of ElectricCharge?

**Comment by sumghai** [comment]
Here's a GIF showing how the blinkenlight LEDs are supposed to work (they cycle through a predefined sequence):

![blinkenlight_debug_1](https://cloud.githubusercontent.com/assets/4993380/8146282/cb8a404c-1283-11e5-88e6-a2bdb89cc4b8.gif)

**Comment by MOARdV** [comment]
The sequence matches what I see (AFAICT).  The problem I have is this:

Prior to activating the animation, all of the lights are off.  This is correct and expected.

Once the animation starts, they blink.  Again, expected behavior.

If I *stop* the animation (set the speed to 0, set the normalized time to 0, which should be the start of the animation loop), some of the lights are still on.  Considering that the animation loop never turns off all the lights, I think this is correct.  What I don't know how to do is to make the lights disappear again.  This is where my ignorance of Unity gets in the way.

As for thresholds: it's somewhat indirect.  What happens is that the value your interested in is normalized and saturated to the range specified in `scale` - eg, if your variable is SYSR_ELECTRIC, and your scale = 1, 5, then the normalized value is 0 for any SYSR_ELECTRIC value less than or equal to 1, and the normalized value is 1 for any value >= 5.  For anything between those values, the normalized value ranges from 0 to 1 (in this case, an electric value of 3 would scale to 0.5).

Threshold looks at the *normalized* value, and treats any normalized value within it's range as "on", and any other value as "off".  In the above example, a threshold of 0.5, 1 would be true any time the real electric value was 3 or greater.  Due to floating point imprecision, it's usually good practice to slightly overlap the two extremes of the range - for instance, use 0.5, 1.001 instead of 0.5, 1.0.  Clear as mud?

**Comment by sumghai** [comment]
>The sequence matches what I see (AFAICT). The problem I have is this:
>
>Prior to activating the animation, all of the lights are off. This is correct and expected.
>
>Once the animation starts, they blink. Again, expected behavior.
>
>If I stop the animation (set the speed to 0, set the normalized time to 0, which should be the start of the animation loop), some of the lights are still on. Considering that the animation loop never turns off all the lights, I think this is correct. What I don't know how to do is to make the lights disappear again. This is where my ignorance of Unity gets in the way.

Ooh, lemme see...

Keyframe 0, the start of the animation, has the lights still on. I'm not sure if this may help, but I could make the lights off in Keyframe 0 - but would this mean during the loop, the lights will be off momentarily? (This isn't really desirable, since the POWER lights need to be on constantly between cycles)

In other words, do I need to reserve on frame in the animation for the off state?

>As for thresholds: it's somewhat indirect. What happens is that the value your interested in is normalized and saturated to the range specified in `scale` - eg, if your variable is SYSR_ELECTRIC, and your scale = 1, 5, then the normalized value is 0 for any SYSR_ELECTRIC value less than or equal to 1, and the normalized value is 1 for any value >= 5. For anything between those values, the normalized value ranges from 0 to 1 (in this case, an electric value of 3 would scale to 0.5).
>
>Threshold looks at the normalized value, and treats any normalized value within it's range as "on", and any other value as "off". In the above example, a threshold of 0.5, 1 would be true any time the real electric value was 3 or greater. Due to floating point imprecision, it's usually good practice to slightly overlap the two extremes of the range - for instance, use 0.5, 1.001 instead of 0.5, 1.0. Clear as mud?

Clear as mud I'm afraid :/

**Comment by MOARdV** [comment]
>Ooh, lemme see...
>
>Keyframe 0, the start of the animation, has the lights still on. I'm not sure if this may help, but I could make the lights off in Keyframe 0 - but would this mean during the loop, the lights will be off momentarily? (This isn't really desirable, since the POWER lights need to be on constantly between cycles)
>
>In other words, do I need to reserve on frame in the animation for the off state?

Based on how RPM current manages starting / stopping animations, yes.  If someone who knows Unity can tell me how to make the animation disappear, then no.  I agree that having a keyframe where all the lights are off would look bad, so let me keep poking at it, and see if I can tap the KSP plugin community on the forum to get a clue how to tell Unity to hide the animation.

> Clear as mud I'm afraid :/

Sorry...  Let me try a different explanation:

```
variableName = GFORCE
scale = 0, 5
threshold = 0.9, 1.001
```
These are the values I use for my "HIGH G" warning lamp in the IVAs I've done.  The variable I'm tracking is GFORCE.  The scale I'm using is 0, 5.  What this means is that any GFORCE less than 0 is treated as 0.  Any GFORCE above 5 is treated as 5.

For thresholding, these values are normalized - which simply means they're scaled between 0 and 1.  In this example, we can convert from the scale of 0,5 by dividing by 5.  Thus, we get a normalized value of 0 for 0G, and a normalized value of 1 for 5G.  The numbers used in the threshold range (0.9, 1.001 in my example) describe the range of normalized values where the test is active - when the normalized GFORCE value is 0.9 or higher, the High G alarm is activated.  Since I had to divide scale by 5 to get the normalized value, I can multiply the threshold value by 5 to convert it back to Gs - my alarm threshold is 0.9 normalized, which translates to 4.5G (0.9 x 5), so my High G alarm is set to 4.5G.

Anyway, your case is much simpler - the SYSR_ELECTRIC scale is 0, 1, so the threshold is a direct translation of the energy/battery level (no multiplication or division required).  If you want your blinkenlichten to shut off if the power is below 0.5 EC, you would use  `threshold = 0.5, 1.001`.  If you want the lights to shut off when the power is below 0.1 EC, you'd use  `threshold = 0.1, 1.001` instead (you use an upper bound slightly larger than 1 due to quirks in floating point maths).

**Comment by sumghai** [comment]
I think I understand `scale` and `threshold` better now - I should probably tweak my CFG values later today.

**Comment by sumghai** [comment]
Here's an idea for the keyframe issue - perhaps one could, through hardcoding or otherwise, reserve the first frame to represent the animation's off state, and have the actual animated loop ignore that first frame completely.

If this was the case, I easily insert a new keyframe at the start where all the lights are off.

What do you think?

**Comment by MOARdV** [comment]
I had considered that possibility before I got side-tracked redesigning the HUD code.  I haven't checked to see if Unity's animation system readily allows for it.

By the way, I released a dev build of RPM today on [DropBox](https://www.dropbox.com/s/zzjuxnnn7mwf07x/RasterPropMonitor-dev.0.21.0.zip?dl=0) that has the fixes from earlier in this thread.

**Comment by sumghai** [comment]
>I had considered that possibility before I got side-tracked redesigning the HUD code. I haven't checked to see if Unity's animation system readily allows for it.

On second thoughts, having done some Googling, it seems that there isn't an intuitive way for Unity to jump to / start from a certain frame, only from a certain time index (which is dependent on framerate).

>By the way, I released a dev build of RPM today on DropBox that has the fixes from earlier in this thread.

Okies, I'll let my beta testers know :)

**Comment by sumghai** [comment]
Having participated in the discussion on the forums regarding the plugin side of things, I think the best thing to do is for me to create a second, separate off-state animation, and have your plugin switch to playing that when resources are depleted.

Thoughts?

**Comment by MOARdV** [comment]
I think that will work.  I'd propose that you put the updated .mu file somewhere I can grab it, and let me know the second animation's name, so I can confirm everything works as expected without further changes to the model.

**Comment by sumghai** [comment]
Just updated the .mu file - there is now an additional off-state animation called `RackLedBlinkerOff`

https://github.com/sumghai/FusTek_StationParts/raw/a802902e4d653ecc226ba8a0ff8c939a6ba2766f/GameData/FusTek/Station%20Parts/Props/Structural/FusTek_WhitePanel_StandardRack.mu

**Comment by MOARdV** [comment]
Good news: it works. The only issue I see is that I think the blinking animation finishes playing before shutting off, so there's a small delay before the lamps go dead.  You will need to add

`stopAnimationName = RackLedBlinkerOff` 

to the JSIVariableAnimator config.  I will get a test build out soon.

**Comment by sumghai** [comment]
> Good news: it works. The only issue I see is that I think the blinking animation finishes playing before shutting off, so there's a small delay before the lamps go dead.

Excellent!

I'm not too fussed about the blinking animation having to finish before shutting off - electronics often have capacitors that hold some charge even after being deprived of power, so it's conceivable that the lights remain on for a brief moment.

Alternatively, I could shorten my looped animation and make the effect less noticeable, but that's my problem, not yours :P

Mucho gracias again, @MOARdV.

**Comment by MOARdV** [comment]
No problemo, @sumghai - I will have a KSP 1.0.3 release Real Soon (TM), since they dropped it today (although it looks like the current RPM works with 1.0.3)

**Comment by sumghai** [comment]
Sorry to bother you again, @MOARdV - I've just got back into working on FusTek recently, and after migrating my latest revamp from KSP 0.90 to 1.0.5, I've found that the internal rack blinkenlights no longer seem to loop.

The lights do shut off when ElectricCharge runs out and turn back on when EC is restored, so I know that JSIVariableAnimator is definitely working. The debug log also states that the props have been configured properly, so I'm puzzled as to why the looped animation isn't running:

![log](https://cloud.githubusercontent.com/assets/4993380/13453806/cbe615c2-e0b7-11e5-9a3b-3fdd5716911a.PNG)

**Props Affected (Model + CFG)**
- [FusTek_WhitePanel_StandardRack.mu](https://github.com/sumghai/FusTek_StationParts/blob/9929969a19f128d196511d4171bd31e959bbdd40/GameData/FusTek/Station%20Parts/Props/Structural/FusTek_WhitePanel_StandardRack.mu)
- [FusTek_WhitePanel_StandardRack.cfg](https://github.com/sumghai/FusTek_StationParts/blob/9929969a19f128d196511d4171bd31e959bbdd40/GameData/FusTek/Station%20Parts/Props/Structural/FusTek_WhitePanel_StandardRack.cfg)
- [FusTek_WhitePanel_StandardRackEva.cfg](https://github.com/sumghai/FusTek_StationParts/blob/9929969a19f128d196511d4171bd31e959bbdd40/GameData/FusTek/Station%20Parts/Props/Structural/FusTek_WhitePanel_StandardRackEva.cfg)

**Mods**
- JSI RPM 0.24.2
- ModuleManager 2.6.18
- FusTek Station Parts ([dev build snapshot 9929969](https://github.com/sumghai/FusTek_StationParts/tree/9929969a19f128d196511d4171bd31e959bbdd40))

**Comment by MOARdV** [comment]
I finally got around to looking at this bug.  Sorry it too so long.

For looping animations, the config requires
```
animationSpeed = n
```
If animationSpeed is not present, it defaults to zero.  When I added `animationSpeed = 1.0` to both of the configs, the blinkenlichten work.

**Comment by sumghai** [comment]
I'll give it a try tonight, thanks!

Sincerest apologies for the PEBKAC on my part ;)

**Comment by sumghai** [comment]
Fix confirmed working - this can be closed now :)

Thanks again!
