### ISSUE TITLE
Allow contents of a transparent pod to be seen when viewed from the IVA of another pod

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#237]
Back when Mihara and I were developing the earliest iteration of [JSITransparentPod] (https://github.com/Mihara/RasterPropMonitor/wiki/Part-modules#jsitransparentpod), we encountered a problem that resulted in the current implementation being partially-gimped

Because IVA space (currently) uses a different coordinate system compared to the pod's orientation, when viewing the contents of one transparent pod from the IVA of another pod, the other pod's internals/Kerbals get doubled up/oriented in a weird manner. Mihara's workaround at the time was to simply disable transparent pod rendering while in IVA, by using an alternative shader to cover up the mess.

I've since raised the issue (along with the [IVASun problem](61)) to SQUAD developer **Mu** via IRC, and this was his response:

> **Mu:**
>i can open up internal camera
>
> **@sumghai:**
> The problem is that, with Mihara's transparent pod plugin, if you try to look at one transparent pod from the IVA of another transparent pod, camera shenanigans means that the internals of one or both transparent pods are either doubled-up or oriented wrongly. Mihara bashed his head in trying to solve this issue
>
> **Mu:**
> yeah the original design brief was against that sort of thing
>
> **@sumghai:**
> I see.
>
> **Mu:**
> but i will open up internal camera a little. not much really to play with in there tbh

Yesterday, I poked **Mu** via PM for a status report on the issue:

> **Mu:**
> Errrrrrrrm..... I cant recall. I might have made some more stuff public for you but i'm not entirely sure. You'll have to check. 

I think it would be nice to take another look to see which methods for IVA Camera / IVA Space / IVA Sun are now publically accessible, so that we may fix this for good.

@MOARdV - if you want, I can go fetch my old correspondence with Mihara from when we first discovered the problem during development

**Comment by MOARdV** [comment]
I'd like to see the old correspondence - I wasn't involved with JSITransparentPod in any way, so it's a bit of a black box (less so now than a month ago, but still).

**Comment by sumghai** [comment]
Okies, here it is:

![aaa](https://cloud.githubusercontent.com/assets/4993380/7848477/2ae25988-0520-11e5-91c4-fc1516bbcc1c.png)

(That's my old email address. by the way - the website no longer exists)

**Comment by sumghai** [comment]
Basically, the reason I raised this issue is because **Mu** claimed that he *might* have opened up the associated KSP classes that we *might* be able to use the solve the problem, so I was wondering if you had some time to perhaps look into it...someday :)

**Comment by MOARdV** [comment]
@JPLRepo - do you think we can trigger or toggle the transparency feature while in IVA?  If we can, I think that solves this issue.

**Comment by JPLRepo** [comment]
The new JSIAdvTransparentPods de-activates on the following conditions in Flight Mode:
Stock IVA Overlay is ON or Current Camera mode is NOT flight (IE: IVA or Map).
and re-activates for the opposite conditions.
Also, the new JSIAdvTransparentPods uses a different method for showing the IVAs in flight.
Mihara's old way was to re-orientate and re-position the IVA model to match worldspace orientation and then change the main cameras to show the IVA Unity layer.
The new module doesn't move or rotate the IVA models at all or change the main cameras.
Instead it creates a new camera OVER the main cameras that only shows Internal space and then rotates this camera so that it aligns with worldspace. The end result being aligned worldspace and internalspace. I believe these issues should be fixed with the new module.

**Comment by MOARdV** [comment]
> I believe these issues should be fixed with the new module.

although

>Stock IVA Overlay is ON or Current Camera mode is NOT flight (IE: IVA or Map).

means that JSIAdvTransparentPods is disabled from IVA, so it's not currently possible to view them from a given craft.  Wait, doesn't KSP just overlay the IVA on top of the regular camera view anyway?  So the stock method may be a problem regardless, because we may see another IVA overlaid on our ownship IVA.

**Comment by JPLRepo** [comment]
Not sure... I'll read everything again. and do some testing.

**Comment by JPLRepo** [comment]
So more reading and thinking on this. Yep I think allowing JSIAdvTransparentPods to show in IVA mode will create artefact issues because of the overlaying camera effect. I'll do some testing.

**Comment by JPLRepo** [comment]
Porting this issue across to new JSIAdvTransparentPods Project and this isue can be closed.
https://github.com/JPLRepo/JSIAdvTransparentPods/issues/2
