### ISSUE TITLE
ADI Instrument + alarm silencing

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#257]
I have 3 question:
1. I was wondering if there is anyway to remove the prograde icon from the ADI and heading bar.
2. Can I make a button that silences but doesn't turn off an alarm. I know that I can currently silence it by clicking on it but I have multiple alarms of the same type and I need to click on all of them to silence them so I need a single button that is capable of muting all the alarm. 
3. Is there any sort of ADI prop, like a flat navball or a small screen with an ADI on it.

Sorry for the nature of this

**Comment by MOARdV** [comment]
Quick reply to 1 and 3 (2 will require more explanation, and I'm at work)

1 - Sort-of, yes: in the JSIHeadsUpDisplay module config add/change:

```
showHeadingBarPrograde = false
progradeColor = 0,0,0,0
```

The first should be self-explanatory for the heading bar.  The second one changes the prograde icon on the ladder to clear, so it won't be visible.

3 - No, no special prop, unless you count the HUD.  You can use the existing MFD prop to display the ADI (if you click the navball page button in the default RPM MFD, you can show the HUD).

**Comment by MOARdV** [comment]
2 - Probably the best way to implement this is to have a master alarm variable that triggers the audio cue.  If you create a custom variable, you can OR together all of the alarms that you want to have an audible component so that if any of them activates, the master alarm variable triggers the audio.  You'd have a single button to press to stop the audio.

**Comment by DeputyLOL** [comment]
Yeah I kind of already have something like that, but I have 2 master alarm, one on each side.
Also the master alarm comes on with other audible alarms and I want to know if there is a way to silence all of them with one button. Thanks for the reply

(What would be really cool is to have a button that 'resets' the master alarm until a new variable is met)

**Comment by MOARdV** [comment]
Disable sound in the other alarms.  Only have visual cues on them (indicator lamps), so that only the master alarm triggers an audible alert.

A reset button would be cool, but it'd require a bit of code - the master alarm would have to become a module, instead of just a custom variable, so that it could keep track of which alarms have been triggered, and how recently the "ignore" button was set.  It's not difficult to write, and I can add it to my future feature list.

**Comment by DeputyLOL** [comment]
That would be really cool, thanks a lot!

**Comment by MOARdV** [comment]
By the way, with the redesign of the HUD, I added a config option `showLadderPrograde`, so you can now turn off the prograde icon on the ladder (as well as turning it off on the compass strip).  That's in the current dev build, and it'll be in v0.21.0 when it officially releases.
