### ISSUE TITLE
Request: Named Stored Strings

### ISSUE THREAD

**Issue by Tahvohck** [Mihara/RasterPropMonitor#274]
Can the storedStrings functionality be modified so that the strings can also be defined and accessed with a name? Something like `storedString = Option_1, release balloons` that could be accessed later as `storedString_Option_1` and would return "release balloons" would be very helpful for making MFD pages where different authors rename the buttons and provide a custom page. Obviously that'd open space for collisions, but that's a problem to be solved with ModuleManager instead of RPM.

**Comment by MOARdV** [comment]
I don't plan on modifying the existing storedString mechanism, since that would require me to support two methods or force IVA makers to update their IVAs.  I think what you're looking for is possible with RPM currently, since the SELECT_ custom variables allow a single named variable to return multiple values - all someone would have to do is add to the VARIABLE_DEFINITION list inside the SELECT_ variable's definition.  The current version of RPM supports the use of strings as the values in the SELECT_ by prefixing the string with a '$' character.
