### ISSUE TITLE
Double free or corruption on Linux 64 bit

### ISSUE THREAD

**Issue by BinaryLinguist** [Mihara/RasterPropMonitor#298]
The following 2 files cause a 'double free or corruption' error in the Linux 64 bit version.  Removing them allows the game to load normally.
* JSI/RasterPropMonitor/Library/Components/HUD/ladder.dds
* JSI/RasterPropMonitor/Library/Components/NavBall/NavBall000.dds

The same issue [here](https://github.com/KospY/KIS/issues/60) was caused by one of the .dds files not having it's resolution reduced.  I'm not sure whether this is the case here because, while ladder.dds is 1.4 MB, hud-overlay.dds is also 1.4 MB and does not cause the error and NavBall000.dds is only 120.8 KB but still causes it.

Launching the 32 bit executable does not cause the error but due to an unrelated problem I can't use it for my main install.

Tested in a fresh install of KSP 1.0.4 with RPM 0.21.0 on Linux Mint x64.

**Comment by MOARdV** [comment]
I haven't found information on the root cause of this error (I don't see anything helpful in a google search).  I've asked KospY about the change in his project, but, without evidence that it's a bug on my part (as opposed to a Unity 64 bit bug), I won't make changes to the RPM package.  I am willing to include legacy format textures in future updates for Linux 64 users.

**Comment by BinaryLinguist** [comment]
Like I said I'm not completely sure it's  the same problem.  I only mentioned it because the file sizes were similar (1.4 vs 1.5 MB).  I unfortunately don't know enough about how textures are loaded in KSP/Unity to comment on what exactly the problem is.

I think legacy textures are a good option unless someone with more knowledge on the subject has a better solution.

**Comment by danfarnsy** [comment]
Running 64-bit KSP in Ubuntu 14.04, I have also been unable to replicate this bug. I am currently working on fixing the B9 Aerospace MFD config files, but the "stock" interfaces from RPM run on my installs without any issues.

**Comment by MOARdV** [comment]
@danfarnsy - thanks for the data point.  It looks like this may be a quirk specific to some flavors of Linux, perhaps.

**Comment by MOARdV** [comment]
I've adjusted the size of the ladder.dds file to be a power-of-2 (it was 512 x 2044), and I have put it on [DropBox](https://www.dropbox.com/s/wqhmekylfc310am/RasterPropMonitor-dev.0.23.0.zip?dl=0).  @BinaryLinguist  - if you're able to do so, would you be willing to extract the ladder.dds from the DropBox zip file and replace it in your KSP install (and remove any ladder.png or other formats if you're using them) to see if it still generates an error?

**Comment by BinaryLinguist** [comment]
The new file seems to work fine.  If you don't mind...where did you find this solution (or was it something you came up with)? I would be interested in reading more about what causes this, if it's available.

**Comment by MOARdV** [comment]
It was an educated wild guess, to be honest.  The DDS was not a power-of-2, and that should not matter for modern video cards.  However, it also had mipmaps, and due to restrictions on block compression (DXT1 / DXT5), the level 1 (and all smaller) mipmap had to be padded to reach the multiple-of-4 required by the BC format.  My guess is that there was a driver or hardware restriction that affected some GPUs, or something odd going on with Paint.NET (which I used to convert it from PNG to DDS).  I've got a Windows system and an NVIDIA 670 GTX, and it appears not to affect me.  The navball texture you've had trouble with is also not a P2 texture, although I don't know if I can resize it successfully (without degrading image quality).  If I can find a size that works and looks okay, I will update it as well.

**Comment by MOARdV** [comment]
I just updated again, this time with a new NavBall000.dds.  If my hunch about the problem is right, this should also start working for you (fingers crossed).

**Comment by BinaryLinguist** [comment]
Yep, looks good!  I also wanted to say thanks for spending the time to fix this, especially given how much of a niche case it is.

**Comment by MOARdV** [comment]
Thank you for confirming the fix.  I'll have an official release some time in the future (before October, I expect), but you should be safe using the dev build until then (or you can revert to v0.22.2 and replace the two textures with the textures in the dev build).
