### ISSUE TITLE
FusTek Station Parts implementation of JSITransparentPod causes significant impact on game performance

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#309]
I've recently received a number of user complaints that the latest dev build of FusTek Station Parts causes significant performance hits in KSP when used in conjunction with JSI RPM (as recent as 0.21.1) - specifically, vessels with station modules that use JSITransparentPod causes the game to load and respond very slowly, in some cases causing crashes to desktop (CTD).

Of all the users, @Starwaster was the only person who provided detailed results from testing my parts, as due to my present circumstances, I don't yet have a computer capable of running KSP to test for myself:

- Apparently it isn't a drop in FPS; vessel load times, right-click context menus, UI elements (e.g. throttle), non-FusTek animated parts simply respond very slowly; in some cases, the game crashes to desktop with no logs (not sure why no logs?)

- Back when @Mihara first developed JSITransparentPod, we noted that lighting transforms would exacerbate the issue greatly; experiments involving a dummy transparent pod containing a few basic RPM MFDs suggested (at the time) that if the IVA had no lighting transforms, we could use at least 28 transparent pods on the same vessel with no appreciable performance drop, while if the IVA had lighting transforms, only 3~4 pods could be used before noticeable performance drops are observed

- As per the previous point, I recently removed the test lighting transforms from the FusTek IVAs, but according to Starwaster, there was no observable improvement

- I also attempted removing most of the looped prop animations, but again, no observable improvement

- @Starwaster noted that the also-transparent Kupola seem to perform better than the Karmony crew modules; the main difference between their IVAs is the the Kupola currently has no detail, while the Karmony crew modules have mid-to-high fidelity of detail, equivalent to ALCOR; that being said, they are mostly visual meshes with a handful of colliders for buttons and controls

- There is no NullRef or similar log spam in the debug console during the slowdown

After a brief discussion with @MOARdV, it's possible that we may be hitting the upper limits of what KSP and Unity can handle (not sure if KSP's upcoming engine migration to Unity 5.x would be of any help).

I would prefer not to disable transparent windows altogether on my modules, but in the worst-case scenario, I may need to consider that final option.

**Parts affected**
 - Karmony Hab Module
 - Karmony Sci Module
 - Karmony Util Module
 - Kupola Observation Module

**FusTek Dev Build Location**
https://github.com/sumghai/FusTek_StationParts/archive/master.zip

Note that the contents of the aforementioned download link will automatically be updated whenever I push commits to it.

**Comment by sumghai** [comment]
Just a stab in a dark, but would specifying a long(ish) `refreshRate` do any good?

I've currently omitted `refreshRate` from the looped animation props, so perhaps my parts are forcing KSP to check variables too frequently, hence the slowdown?

**Comment by MOARdV** [comment]
With the exception of the MFD monitors and the variables refresh system, everything in RPM shuts down when the user is outside the craft, so there should be very little happening computationally.  I will experiment with shutting down those remaining components to see if that makes an appreciable difference in performance, which may help distinguish whether it's RPM overhead, or Unity/KSP overhead that's the issue.

**Comment by MOARdV** [comment]
Here are some very preliminary results.  The craft I worked with uses a single RC-L01 2.5m Squad core as the root part (building in the SPH to have a horizontal default layout).  I added a hab module on one end and a sci module on the other, and then launch clamps.  FPS measurements based on sarbian's GC monitor, with numbers estimated, since there's a lot of noise in that value.

In the SPH, frame rate drops significantly with each transparent part (~59fps for the probe core, ~49fps with the Hab added, and ~25fps with the Hab + Sci).  This is on a reasonably powerful desktop computer (quad core i5 3570K, ~3.7GHz with GTX 670 graphics).  Launching the craft and sitting at the runway until terrain loads, the game stabilizes around 21-24 fps.

If I disable the monitors and the RPMC module while external to the craft, there is no appreciable impact.

Since it doesn't appear that the core RPM functionality is significantly affecting performance, I took a look instead at what the JSITransparentPod is doing every frame.  I added some logging to OnUpdate, and one thing that jumped out at me right away: OnUpdate takes on the order of 5-7 milliseconds *per part per update*.  60fps is about 16ms per frame.  Adding 5ms puts us about 21ms per frame, or 48fps.  Adding another 5ms puts us at 26ms, or 38fps.  I am reasonably sure this is our performance killer.

I will look closely at what's being done per frame and see if it *must* be done every frame, or if it can be done once and ignored until something changes (maybe using a callback method, if the right event exists, instead of a polling per update).

**Comment by MOARdV** [comment]
The updates need to happen per-frame, or the interiors won't show up, so that's not a solution.  I don't know enough about what happens under the hood in KSP / Unity to know what other things I can try, so I will have to do some research, and maybe ask some questions on the KSP forum to see if anyone has ideas for how to improve the performance.

**Comment by sumghai** [comment]
Thanks for looking into this for me, @MOARdV. 

I've seen users do crazy stuff with FusTek, like make rotating rings out of 10+ habitat modules, so in the meantime, perhaps I should seriously consider making the Karmony module windows non-transparent.

**Comment by MOARdV** [comment]
As a user, I think the portholes are too small to really fully appreciate the interiors, particularly from any distance beyond immediate proximity.  On the other hand, the cupola is an excellent candidate for transparency, since it likely won't have an incredibly complex interior (assuming the number of components affects frame rate similarly to part count on craft).  It might be possible to toggle transparency when the shutters on it close, so there's no extra performance cost to having the cupola when it's buttoned up.

I will continue putting effort into trying to find a way to improve the transparency performance, but (at least right now) I don't have enough insight to make appreciable improvements.

**Comment by sumghai** [comment]
In which case, I think it's definitely wise if I removed the transparent pod feature on the Karmony crew modules. I believe the performance hits are due to the "modular" panel system I used to build up their IVAs.

As for the Kupola (which will definitely remain JSITransparentPod-powered), I'll do my best to keep props to a minimum, just some handrails, RPMs, a handful of buttons, chairs and maybe a laptop stand.

**Comment by sumghai** [comment]
Oh, as an afterthought on this:

One of original intentions for transparent windows on the Karmony modules is that if the interior is lit, the window shutters can selectively block out light from certain viewports.

Now that the Karmony module windows are opaque again, making those windows glow at night would be a bit more difficult. Before JSI RPM, each module had emssive animations that made all the viewports glow at the same time.

Given that there are window shutter IVA props, this means that no matter what state those shutters are in, the windows will still glow at night.

The ultimate workaround would involve complex interaction with JSI RPM, props and action groups, which might be a bit difficult. More on that later.

**Comment by MOARdV** [comment]
Mihara implemented methods to control external animations from props.  That would likely present a way to manage the shutter/glow behavior.  There might be some work needed to add the master switch + individual switch functionality, but I suspect RPM is most of the way to supporting that behavior already.

**Comment by sumghai** [comment]
> Mihara implemented methods to control external animations from props. That would likely present a way to manage the shutter/glow behavior.

Indeed. I originally planned to use that method to control the Kupola blast shutters from the Kupola IVA, so it shouldn't be too difficult to do something similar for the Karmony modules.

The window glow emissives might get a little complicated, especially as some modules have different lighting "zones":
 - Hab module has five; one for the galley, and four for each of the bunks
 - Sci and Util module has one zone for the entire cabin

But that's for me to worry about :)

> There might be some work needed to add the master switch + individual switch functionality, but I suspect RPM is most of the way to supporting that behavior already.

I see - sounds good.

**Comment by Starwaster** [comment]
I've looked at some of the code involved re: update frequency.

I agree that a lot of that has to happen in Update (or LateUpdate), but some of it definitely does not and should be moved to FixedUpdate() which often runs less frequently. (though if framerate is low, it could run more frequently but it always runs at a fixed rate)

For instance, you have code that checks kerbal seating, presumably to validate kerbal seat assignment. Don't do that every frame. Instead, either 

* Move that to FixedUpdate() because kerbal assignment changes can only happen on FixedUpdate anyway. (always keep a mind towards whether or not the thing you're checking for can reasonably change from Update to Update. If you're going to have 3-5 Update cycles between two FixedUpdate() and event X can only happen in a FixedUpdate then it's being checked for unnecessarily in Update)
* Even better is move that Kerbal checking to an event and don't check for it in FixedUpdate() either. Bind to the GameEvents onCrewBoardVessel, onCrewTransferred, onCrewKilled and onCrewOnEva. Then do your checks in there.

**Comment by MOARdV** [comment]
@Starwaster - I'm not a Unity guy.  Can you point me at a resource that tells me what things in KSP are updated in FixedUpdate vs. Update, so I can more intelligently split update functionality?

**Comment by Mihara** [comment]
@MOARdV :

http://answers.unity3d.com/questions/10993/whats-the-difference-between-update-and-fixedupdat.html
http://docs.unity3d.com/ScriptReference/MonoBehaviour.FixedUpdate.html
http://docs.unity3d.com/ScriptReference/MonoBehaviour.Update.html

Basically, Update is a screen frame, while FixedUpdate is a physics frame. Notice that KSP modules are meant to use OnUpdate and the like *(most of the time)*, which are ultimately methods called by the vessel's Update() - but that is not necessarily true for InternalModule. It's not exactly trivial what is best to do when, which is why I originally I just dumped everything into Update(). Latching onto events whenever possible would be far superior, only, I never found out just what kind of cleanup would I be supposed to do when the internal is destroyed - which, as you know, happens bloody often.

**Comment by MOARdV** [comment]
@Mihara - Ah, thanks.  I guess it's past time for me to put off learning about some of this. :)

**Comment by MOARdV** [comment]
This isn't a fix for the performance problem, but the code changes from JPLRepo for Issue #361 (in pull request #369) provide end-users a way to bypass the problem.  The downside is that it would require the FusTek station parts to implement "window covers" that are used when the IVA is not rendered to prevent see-through parts.

There is also Pizzaoverhead's [FreeIVA](http://forum.kerbalspaceprogram.com/threads/131439) that appears to draw multiple IVA without the lag.  I have not inspected the mod nor source myself, so I don't know if there's anything it does that could be leveraged into RPM.

**Comment by sumghai** [comment]
> This isn't a fix for the performance problem, but the code changes from JPLRepo for Issue #361 (in pull request #369) provide end-users a way to bypass the problem. The downside is that it would require the FusTek station parts to implement "window covers" that are used when the IVA is not rendered to prevent see-through parts.

Once I get a new laptop and resume work on FusTek, my plan is to make the hab/sci/utils viewports non-see-through by default, and use a combination of JSIAnimator references to part exterior animations, emissives and transparent textures to emulate viewport shutters / window lights (sumghai/FusTek_StationParts/issues/69).

> There is also Pizzaoverhead's FreeIVA that appears to draw multiple IVA without the lag. I have not inspected the mod nor source myself, so I don't know if there's anything it does that could be leveraged into RPM.

That's another possibility, although I suspect that the lag mainly comes from the highly detailed interior of FusTek modules themselves, compared to stock modules.

**Comment by JPLRepo** [comment]
The end-user config option to turn off the transparentPod setting will help I believe. But as MOARdV said you need to implement opaque windows and use transparentShaderName var to have JSITrasparentPod automatically switch them to transparent.. or you could do as you said and implement shutters/lights, but I think they would need to synch with the end-user transparency setting?

I'm looking at an option to turn off props as well. Do we think this is a good idea or not?
One idea is to turn them all off when in external view.. OR.. you could specify a list of props in the config vars like transparentShaderName so only selectively turn off props when in external view.
What do you think?

**Comment by sumghai** [comment]
> The end-user config option to turn off the transparentPod setting will help I believe. But as MOARdV said you need to implement opaque windows and use transparentShaderName var to have JSITrasparentPod automatically switch them to transparent.. or you could do as you said and implement shutters/lights, but I think they would need to synch with the end-user transparency setting?

To integrate everyone's ideas, I'll make a new model called **KarmonyViewport**, consisting of the following submeshes:
 - **frame**, the round outside frame of the viewport. KSP Specular shader and always opaque.
 - two separate panes of "glass"
     - **pane_outer**, the pane exposed to the outside of the craft. KSP Alpha shader and always transparent
     - **pane_inner**, the pane facing the inside of the craft. KSP Emissive shader and opaque ***by default***, but can be made transparent via ***JSITransparentPod/transparentShaderName***
 - **shutter**, the animated shutter sandwiched between the two window panes. KSP Specular shader and always opaque.

This setup means quite a bit more work for me, but would ensure compatibility with end-user transparency settings.

> I've also moved the portraitcams code out of OnUpdate and into GameEvents as was suggested earlier by Starwaster but I haven't pushed that change to the main branch yet.

I see.

> I'm also looking at an option to turn off props as well. Do we think this is a good idea or not?
One idea is to turn them all off when in external view.. OR.. you could specify a list of props in the config vars like transparentShaderName so only selectively turn off props when in external view.
What do you think?

Selectively hiding props beyond a certain draw distance is an excellent idea - perhaps an "opt-in" approach would be best, as it's easier to specify what to keep drawn than to list all the ones that need to be hidden

e.g. a bubble cockpit has several props, ranging from a few large items like the seat and internal wall panels to hundreds of labels, RPMs and buttons. The mod author can list just the few large props to keep, while the rest are automatically assumed to be undrawn at sufficient distance.

Clear as mud? ;)

**Comment by JPLRepo** [comment]
> The end-user config option to turn off the transparentPod setting will help I believe. But as MOARdV said you need to implement opaque windows and use transparentShaderName var to have JSITrasparentPod automatically switch them to transparent.. or you could do as you said and implement shutters/lights, but I think they would need to synch with the end-user transparency setting?
>> To integrate everyone's ideas, I'll make a new model called KarmonyViewport, consisting of the following submeshes:

>> frame, the round outside frame of the viewport. KSP Specular shader and always opaque.
two separate panes of "glass"
>> pane_outer, the pane exposed to the outside of the craft. KSP Alpha shader and always transparent
>> pane_inner, the pane facing the inside of the craft. KSP Emissive shader and opaque by default, but can be made transparent via JSITransparentPod/transparentShaderName
>> shutter, the animated shutter sandwiched between the two window panes. KSP Specular shader and always opaque.
>> This setup means quite a bit more work for me, but would ensure compatibility with end-user transparency settings.

This would work.

> I've also moved the portraitcams code out of OnUpdate and into GameEvents as was suggested earlier by Starwaster but I haven't pushed that change to the main branch yet.
>> I see.   

I've created a pull request for this, MOARdV to incorporate in next release in the next few days. This saves a fair bit of unnecessary processing every frame.

> I'm also looking at an option to turn off props as well. Do we think this is a good idea or not?
One idea is to turn them all off when in external view.. OR.. you could specify a list of props in the config vars like transparentShaderName so only selectively turn off props when in external view.
> What do you think?
>> Selectively hiding props beyond a certain draw distance is an excellent idea - perhaps an "opt-in" approach would be best, as it's easier to specify what to keep drawn than to list all the ones that need to be hidden

>> e.g. a bubble cockpit has several props, ranging from a few large items like the seat and internal wall panels to hundreds of labels, RPMs and buttons. The mod author can list just the few large props to keep, while the rest are automatically assumed to be undrawn at sufficient distance.

>> Clear as mud? ;)

Clear as. I was thinking along these lines. But - have to be careful not to make it too onerous as the processing to find and switch off props may be more than just leaving them all on. I'll do some testing as least with the exclude list. The idea based on distance sounds like a lot of calculations that again may undo any efficiency gain. Let me see what I can come up with and whether it really saves anything and report back.

**Comment by JPLRepo** [comment]
JSITransparentPod now has the part menu option to turn transparency on/off/auto per part as well as it turns transparency off when the game camera is more than 100 units away from a part. This seems to have reduced the performance impact. Question is: do these two things now resolve this issue or not?

**Comment by sumghai** [comment]
Let's keep this issue open until I can test it properly - I've only just got back into modding recently, after waiting for nearly a year to buy a new laptop capable of running the game. I'm currently prioritizing 1.05/1.1 compatibility fixes for smaller mods like SDHI SMS and Strobe-O-Matic.

**Comment by JPLRepo** [comment]
NP :)

**Comment by JPLRepo** [comment]
Porting this issue across to new JSIAdvTransparentPods Project and closing this issue.
https://github.com/JPLRepo/JSIAdvTransparentPods/issues/1
