### ISSUE TITLE
Variable for damaged or destroyed parts.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#331]
Parts can sometimes be damaged, destroyed or separated by heat, stress or bad flying.
When this occurs it can be seen on the ship log.

Would it be possible to have a variable that checks to see if something was damaged/destroyed/no longer attached. 

It would probably have to function similar to the master warning feature (if that's going to be implemented). As once something breaks the variable will stay on.

Also is this possible?
https://github.com/Mihara/RasterPropMonitor/issues/304

**Comment by MOARdV** [comment]
I'd say "maybe" it's possible.  I should be able to tell when a part is separated, but I don't know if I can know the reason (for instance, did it separate because it broke, or because you just staged?).  Parts that don't separate (like wheels that are damaged due to overspeed) might have something I can look at to determine if the part's damaged (I have not checked yet).  As for parts exploding due to overheat / collision, I don't know yet.  TL; DR: Maybe.  I will have to do some research.

**Comment by DeputyLOL** [comment]
Ok, I ask this because the log seems to have all the detail.
E.g. 
Structural failure between X and Y
X was damaged by exhaust
X was destroyed by aerodynamic forces
etc.

**Comment by MOARdV** [comment]
I'll look into the callbacks that KSP provides, and ask around.

**Comment by MOARdV** [comment]
At this point, I don't see myself finding a way to do this reliably.
