### ISSUE TITLE
SpaceplaneHoldHeading / Autoland typo

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#385]
Moving discussion from closed issue #362

**Comment by MOARdV** [comment]
Wow.  Epic copy-paste fail.  I've got a typo in the method name - it should be spelled Spaceplane, not Spaceplace.  And, since I was copying that name from the code and pasting it into the test MFD, I didn't see the typo.  Gah!

**Comment by MOARdV** [comment]
This applied to HoldHeading and Autoloand.  Stupid, stupid, and too much time staring at the screen.

**Comment by DeputyLOL** [comment]
:D glad you found the problem!

**Comment by MOARdV** [comment]
The dev build now has the fix. https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

**Comment by DeputyLOL** [comment]
all good so far, except the transfer button doesn't work.

**Comment by MOARdV** [comment]
SpaceplaneHoldAltitude is a getter (getMethod), so it'll fetch the hold altitude from MechJeb.  SetSpaceplaneHoldAltitude is the setter (setMethod) to set it.  It looks like (from the config you had in the other issue), you were using the first method in a setMethod configuration.

**Comment by DeputyLOL** [comment]
ok, thanks for the help. I've noticed that the SpaceplaneAutopilot is still returning as -1.

Any thoughts?

**Comment by MOARdV** [comment]
There isn't a SpaceplaneAutopilot method - there's ButtonSpaceplaneAutoland ... 

D'oh - documentation error (again!).  It's ButtonSpaceplaneAutoland.  I was thinking Autopilot when I was typing.  I'll fix the wiki.

**Comment by DeputyLOL** [comment]
The wiki lied!!! NOOOO!!!!!
Thanks for the correction.

**Comment by MOARdV** [comment]
I'm going to have to fire the guy who edits the wiki.

**Comment by DeputyLOL** [comment]
Would these work in triggers?
would I be able to trigger the autoland to turn off automatically when it reaches the ground?

**Comment by DeputyLOL** [comment]
Now that we can use space plane guidance, I'm desperate to get a basic autopilot system working.
So far I'm really struggling with the landing system. It's supposed to automatically switch off when it goes below 50m and not be able to be turned on under 50m. I tried using triggers and they 'sort' of work but can only be used once due to the autopilot switching off but the switch switches off than on again.
Do you have any ideas?
Switch:
	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = plugin
		masterVariableName = CUSTOM_ALDISCONNECT
		masterVariableRange = -0.5, 0.1
		perPodPersistenceName = AUTOLAND_ON
		switchSound = ASET/ASET_Props/Sounds/B_Button01_Click
    		PLUGINACTION
    		{
		        name = MechJebRPMButtons
		        actionMethod = ButtonSpaceplaneAutoland
		        stateMethod = ButtonSpaceplaneAutolandState
		}
	}

Trigger:
RPM_TRIGGERED_EVENT
{
   eventName = aldisconnect
   variableName = CUSTOM_ALDISCONNECT
   range = 0.5,1.1
   triggerEvent = JSIMechJeb:ButtonSpaceplaneAutoland
   triggerState = false
   //eventState = 
}


Variable:

RPM_CUSTOM_VARIABLE
{
  name = ALDISCONNECT
  operator = OR
  SOURCE_VARIABLE
  {
    name = CUSTOM_ALDISCONNECT_SAS
    range = 0.5, 1.1 
  }
}

RPM_CUSTOM_VARIABLE
{
  name = ALDISCONNECT_SAS
  operator = AND
  SOURCE_VARIABLE
  {
    name = PERSISTENT_AUTOLAND_ON
    range = 0.5, 1.1 
  }
  SOURCE_VARIABLE
  {
    name = CUSTOM_SASDISCONNECT
    range = 0.5, 1.1
  }
}

RPM_CUSTOM_VARIABLE
{
  name = ALDISCONNECT_LANDING
  operator = AND
  SOURCE_VARIABLE
  {
    name = RADARALTOCEAN
    range = 0, 50 
  }
}

**Comment by MOARdV** [comment]
I think I see a bug in the way the "force it to shut off" logic works with plugin actions.

**Comment by DeputyLOL** [comment]
The button presses twice, but the space plane guidance remains on.

**Comment by MOARdV** [comment]
Give me a few minutes, and I'll update the dev build.

**Comment by DeputyLOL** [comment]
ok thanks :)

**Comment by MOARdV** [comment]
Let's take the discussion over to Issue #392.
