### ISSUE TITLE
JSIActionGroupSwitch plugin action / forcedShutdown interaction

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#392]
Spawned from #385 - if we try to force a plugin action off, it ends up ignoring the "force it off" statement, instead using the current state of the plugin.

**Comment by MOARdV** [comment]
Maybe-fix (untested): https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

**Comment by DeputyLOL** [comment]
ill test it now

**Comment by DeputyLOL** [comment]
doesn't work

**Comment by MOARdV** [comment]
Okay.  Looks like the easy answer wasn't the right one.  I'll have to put some more time on it.

**Comment by DeputyLOL** [comment]
I suspect it has something to do with the mastervariable as I think it worked before I added that

**Comment by DeputyLOL** [comment]
but it didn't deliver the needed results

**Comment by MOARdV** [comment]
Okay.  My new working theory is that it's an interaction between the trigger event and the action group switch.  I will have to instrument that code better so I can really see what it thinks it is doing.

**Comment by DeputyLOL** [comment]
Do you think it would be possible to be able to transfer a persistent variable to a different persistent variable?

I ask this because I have an icon on my altimeter bar that displays the selected altitude. It moves up and down as I increase and decrease the target altitude. I want it to stay where it is until I update it with a new altitude.

**Comment by MOARdV** [comment]
It is possible.  Not yet, but maybe soon.

**Comment by MOARdV** [comment]
Another maybe-fix: https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

However, I think what you're trying to do does not require the trigger event.  What you need to do is use the masterVariableName / masterVariableRange to indicate when the switch should be enabled.  For example:
```
MODULE
{
	name = JSIActionGroupSwitch
	animationName = SwitchTumbleAnim
	switchTransform = SwitchColider
	actionName = plugin
	switchSound = ASET/ASET_Props/Sounds/tumbleClick01
	masterVariableName = CUSTOM_MOARdV_ScanEnable
	masterVariableRange = 0.1,1.1
	PLUGINACTION
	{
		name = JSIInternalRPMButtons
		actionMethod = RadarEnable
		stateMethod = RadarEnableState
	}
}
```

This is my switch for enabling the Gemini docking radar in my FASA Gemini pod.  The switch will not work as long as the custom variable is false (=0).  When the custom variable is true (=1), the switch functions normally.  If the switch is on and the custom variable becomes false, the switch turns itself off again, and it stays off.

**Comment by DeputyLOL** [comment]
Not sure about that. 
I disabled my trigger and used a mastervariable. It disabled the switch when it was supposed to, but still didn't turn off the autoland. Leading to my plane crashing because I couldn't navigate the mechjeb menus fast enough.
I then tried again with the trigger enabled. Same result. Except I had the mechjeb window open so I landed safely.

**Comment by DeputyLOL** [comment]
Fixed! Thank you!
