### ISSUE TITLE
JSIEngine - Thrust Reverse/after burner and more

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#430]
We have thrust reverser and after burners now.... yay.

Could there be a way of toggling them from IVA?

**Comment by MOARdV** [comment]
I will take a look and see how they work.  I'll guess the answer is "yes".

**Comment by DeputyLOL** [comment]
great, thanks.

**Comment by MOARdV** [comment]
Thrust reverse is handled by a ModuleAnimateGeneric, so it'll be controlled by action groups.  Adding a special control for it would be a hack that'd be at risk of breaking, so I won't be doing anything special for it.  The afterburners are controlled by MultiModeEngine, which is also what toggles modes on the RAPIER engine.  I can (and will) add support for that.

**Comment by DeputyLOL** [comment]
damn, I was really hoping to be able to use reverse thrust from IVA.
is there really no way of supporting them?

**Comment by Alexustas** [comment]
>Thrust reverse is handled by a ModuleAnimateGeneric, so it'll be controlled by action groups. Adding a special control for it would be a hack that'd be at risk of breaking...

oh. this is very bad news ((

**Comment by MOARdV** [comment]
I've had a cup of coffee now, so I had an idea: what I could do is add a special part module like `JSIThrustReverserControl`.  It'd have to be patched onto engines that have thrust reversers to provide a bridge module so RPM knows what animation the thrust reverser is.  Let me go get some more coffee, and maybe I can make sense of the idea. :)

**Comment by DeputyLOL** [comment]
coffee, the solver all the worlds problems!

**Comment by DeputyLOL** [comment]
actually, while on the subject of engines. Is there a way to 'set thrust' or to maybe 'increase thrust by ...' and 'decrease thrust by ...'?
Just an idea.

**Comment by MOARdV** [comment]
What do you mean by "set thrust" - like "set thrust to 50%", or "set thrust to 10kN" (what units do you want, in other words).  If percent, then yes, that would (should be) easy.

**Comment by DeputyLOL** [comment]
percent

**Comment by Alexustas** [comment]
btw,  how about Thust limit control using numeric input? ))

**Comment by MOARdV** [comment]
> btw, how about Thust limit control using numeric input? ))

Controlling the throttle limit slider?  Yeah, I should be able to do that.  Looks like v0.24.1 will be the RPM Engine Control Update. :)

**Comment by DeputyLOL** [comment]
:D

**Comment by Alexustas** [comment]
:D 
Is it possible to add a variable that displays the number of engines in the current stage?

**Comment by Alexustas** [comment]
and Max/Current tamperature of a hottest engine or may be... an indvidual values for each engine

**Comment by DeputyLOL** [comment]
and maybe the ability to toggle individual engines?

**Comment by MOARdV** [comment]
You guys make it sound like you are playing Kerbal Spaceplane Program.  Rocketships don't need individual engine controls :D

The Multimode Engine (afterburner) thing is more challenging than I expected.  For reasons I have not figured out, the mode control seems not to be accessible in the normal way (typically, there's an action I can trigger that will switch modes).  This may take longer than today to get it working.

**Comment by MOARdV** [comment]
The first part is implemented - toggling afterburners (or otherwise switching modes for multi-mode engines).  Currently, individual engine control is not available, and I need to add some more features before I publicize and document it.

**Comment by DeputyLOL** [comment]
is this in the dev build?

**Comment by DeputyLOL** [comment]
and where can I download the dev build because the forum doesn't exist anymore

**Comment by MOARdV** [comment]
On [DropBox](https://www.dropbox.com/s/gaplio91e94fej1/RasterPropMonitor-dev.0.24.1.zip?dl=0).  The JSIEngine stuff is undocumented right now - I'm still trying to get something put together that will work in a general sense, so I may have to completely change what's there.

**Comment by DeputyLOL** [comment]
Did you add reversers?

**Comment by MOARdV** [comment]
> Did you add reversers?

No.  That's why it's undocumented and incomplete.  At this point, I'm going to release a v0.24.1 build, and then continue working on some other larger features (including thrust reversers and throttle limits as alexustas requested) for a v0.24.2 release later in December.

**Comment by DeputyLOL** [comment]
ohhh..... maybe a Christmas special?

**Comment by DeputyLOL** [comment]
can we have more engine variables. Such as fuel flow?

**Comment by MOARdV** [comment]
> can we have more engine variables. Such as fuel flow?

I will see what variables I can access.  For the initial release, I may not be able to provide per-engine detail.  I still have not come up with a satisfactory way to make that work.

**Comment by DeputyLOL** [comment]
thank you. how are the horizontal bars coming along? I can test them if you want

**Comment by MOARdV** [comment]
Remember to track per-engine fuel flow.

**Comment by MOARdV** [comment]
Reviewing features requested in this issue as of [this update](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0):

* Afterburners (multi-mode engine) - available using JSIRPMInternalButtons `GetEnginesPrimaryMode` and `SetEnginesPrimaryMode`.
* Set Throttle Limit % using `SetThrottleLimit` (number from 0 - 100, not 0 - 1).
* `HOTTESTENGINETEMP` and `HOTTESTENGINEMAXTEMP` - current and maximum engine temperature of the hottest engine (engine closest to its max temp).
*  `ENGINECOUNT` - # engines on current stage.
* `ACTIVEENGINECOUNT` - # engines currently on current stage that are on.
* `CURRENTENGINEFUELFLOW`, `MAXENGINEFUELFLOW`, `CURRENTINTAKEAIRFLOW` - fuel and air flow in grams / second.

Missing features:
* Thrust reverser.  Requires a new part module that has to be added to engines (parts have to opt-in to being controlled).
* Set Thrust to % - I need a reminder on exactly what this is asking for.  Is it "set throttle to this setting", similar to the Full Throttle and Cut Throttle callbacks?
* Individual engine control - this adds a great deal of complexity,  I don't think I will be implementing this any time soon.

**Comment by DeputyLOL** [comment]
This is great. I understand that individual engine control will be difficult but what about individual engine monitoring? 
The ability to read thrust from a certain engine, see a certain engines state (flamout/off/on) etc.?

**Comment by MOARdV** [comment]
> This is great. I understand that individual engine control will be difficult but what about individual engine monitoring? 
The ability to read thrust from a certain engine, see a certain engines state (flamout/off/on) etc.?

I should have stated more broadly "individual engine control / status".  The problems with such an implementation are:

1) Consistently mapping engines to engine IDs - that is, Engine 1 must always be Engine 1, even if the craft stages (discarding engines) or pieces break off.  Adding a part module that provides an engine ID resolves this problem, but...

2) What happens when two or more craft using this feature dock?  Which Engine 1 counts as the "real" Engine 1?  What if they have different settings (Engine 1A is on, Engine 1B is off), or they have different thrust limits, or they're entirely different types of engines?  This becomes a bigger problem with engine control: what happens if I thrust to adjust an orbit, but another craft's engine fires as well because it has the same engine ID?

3) Adding an engine identifier to the plugin methods (like JSIInternalRPMButtons `ButtonEnableEngines`, etc.) - this would require providing an engine selector parameter, and adding the plumbing to convey the selector to the plugin.

4) Many new plugin methods to get to what are currently defined variables (eg `THRUST`).

5) Tracking all of the individual data.  A number of values require pre-processing to derive them from the info KSP provides.  I'd need to do that for each engine that's participating (individually, in addition to collectively for the existing variables), and I'd need to squirrel that individual data away for later use.

6) Defining interactions with non-participating engines.  If the IVA is configured for multi-engine data and control, but none of the engines on a craft have the module, what happens (other than a lot of inactive controls and instruments).

All of this isn't saying "never going to happen", but there are a lot of issues and complexities that need to be hashed out in a way that doesn't impact existing IVA uses (such as lag from increased overhead), and which can provide a satisfactory experience (both for the player and the IVA designer - if it's too complex or finicky, it won't get used).  And right now, I don't have answers that I think will do the job.

**Comment by Alexustas** [comment]
"CURRENTENGINEFUELFLOW" gives zero in the "wet" mode of the engine

**Comment by Alexustas** [comment]
... as well as the `"Trust"`

**Comment by MOARdV** [comment]
Fixed on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by DeputyLOL** [comment]
ok, I see your point. And it is a good point. Ill just be happy with reverses then. As for the reminder of 'set thrust', I think a percentage would do. As you are less likely to get in the situation of trying to set thrust higher than the engine can achieve. If it was a percentage than it would be a lot easier.

**Comment by MOARdV** [comment]
Added JSIInternalRPMButtons `SetThrottle` - uses a number from 0 - 100.

**Comment by MOARdV** [comment]
[DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) with thrust reverser control (tested), SetThrottle (untested), and brake tweakables (untested).

You must add a JSIThrustReverser module to any part that you want controlled by the thrust reverser interface.  It does *not* have to be an engine - all it needs is ModuleAnimateGeneric - which means you can tie other external animations to the thrust reverser control.

For instance, on the J-90 stock engine:
```
@PART[turboFanSize2]
{
	MODULE
	{
		name = JSIThrustReverser
	}
}
```

JSInternalRPMButtons `GetThrustReverserEnabled` returns true if any of the tracked thrust reverser animations are deployed.  `SetThrustReverser` switches them on and off.

Because the thrust reverser is implemented as ModuleAnimateGeneric, I know when it is moving, but not which way, so right now `GetThrustReverserEnabled` returns true if any animation is more than 50% complete, which means animations that rely on that variable will show a delay that depends on how fast the animation is.  I don't have a good solution that doesn't involve additional computations and data tracking, and I don't think it is worth adding that extra complexity.  I could add a variable that reports the average animation position (from 0 - 1) if needed.

**Comment by DeputyLOL** [comment]
> I could add a variable that reports the average animation position (from 0 - 1) if needed.

If its not too much to ask than I think it would be useful to have a position variable for the reversers. :)

**Comment by DeputyLOL** [comment]
Is it ok if i give the link to your dev build to someone who wants to test my cockpit for me?

**Comment by MOARdV** [comment]
> If its not too much to ask than I think it would be useful to have a position variable for the reversers.

I will look into it.

> Is it ok if i give the link to your dev build to someone who wants to test my cockpit for me?

Yes.  The dev builds are publicly posted all over GitHub issues and on the first post in the RPM thread,

**Comment by DeputyLOL** [comment]
thanks and thanks.

**Comment by DeputyLOL** [comment]
as far as I can tell the brake tweakables don't work.

**Comment by DeputyLOL** [comment]
brakes always return -1

**Comment by DeputyLOL** [comment]
[ERR 20:25:27.329] RasterPropMonitorComputer: I failed to find the method for JSIInternalRPMButtons:GetWheelBrakes

[ERR 20:25:27.333] RasterPropMonitorComputer: Tried to look for method with propToUse still null?

**Comment by MOARdV** [comment]
Is that with the latest build on DropBox?  That should have it (I can't check it for a while - got some other things going on today).

Also, how are you using it?  It won't work in a JSIActionGroup, since it's a numeric, not a boolean.  It'd be used for something like an MFD display as PLUGIN_JSIInternalRPMButtons:GetWheelBrakes

**Comment by DeputyLOL** [comment]
I'm using setwheelbrakes in as a transfer action. I used getwheelbrakes in a MFD page exactly as defined above.

**Comment by MOARdV** [comment]
Try downloading the plugin again.  I just updated it, in case the version I posted was from before I had the brakes working.  I verified that the GetWheelBrakes is not returning -1 with it.

**Comment by DeputyLOL** [comment]
If your not busy with that 'thing', I had an idea on how you might achieve individual engine control.
Instead of assigning each engine to a unique number, you assign it to a group.
BULLET POINT TIME!!!!!!
- Multiple engines can be assigned to one group.
- An engine can only be assigned to one group.
- There can be more than one groups.
- An action can be assigned to a group number (on/off, reverse, afterburn...)
- Any actions performed on the group will be performed on all engines in that group.
- Engine related variables can be assigned to a group number (thrust, fuel flow, status).
- Any engine related variable will be an average of all the engines in the group.
- If the ship docks with another ship than any engine with the same group number will become part of the same group.
- If an engine in one of the groups disappears or falls off, engine variables will show an average of remaining engines.
- If a variable is assign to a group that doesn't exsist, return -1.
- If a variable is assign to an empty group or a group where all the engines have fallen off, return -1.

THRUST - displays total thrust for all engines
THRUST_GROUP# - displays total thrust of all engines in group #.

Let me know what you think. :)

**Comment by DeputyLOL** [comment]
Also, finally got round to testing the thrust reversers. The GetThrustReverserEnabled works but the SetThrustReverser doesn't. Also I think it would be useful to have a 0-1 variable for reverser position.

**Comment by MOARdV** [comment]
> Also, finally got round to testing the thrust reversers. The GetThrustReverserEnabled works but the SetThrustReverser doesn't. Also I think it would be useful to have a 0-1 variable for reverser position

I'll look into the SetThrustReverser - it was working last time I checked it.  As for position: it's a generic animation, so I may be able to report the position, but it's not something that can be manipulated.

**Comment by Alexustas** [comment]
I tested this feature and it works fine

**Comment by DeputyLOL** [comment]
ah yes, I forgot to set the switch to be a plugin instead of a dummy.

Sorry about that.

**Comment by MOARdV** [comment]
> ah yes, I forgot to set the switch to be a plugin instead of a dummy.

RPM2 will be easier to work with.  Here's what I have in mind for JSIActionGroupSwitch / JSIVariableAnimator / JSICallbackAnimator / JSILabel / JSIInternalEVAHatch / JSINumericInput / JSIPropTextureShift / JSIVariableLabel: [First Draft Document](https://raw.githubusercontent.com/MOARdV/AvionicsSystems/master/Documents/MASComponent.txt)

**Comment by DeputyLOL** [comment]
> RPM2 will be easier to work with. Here's what I have in mind for JSIActionGroupSwitch / JSIVariableAnimator / JSICallbackAnimator / JSILabel / JSIInternalEVAHatch / JSINumericInput / JSIPropTextureShift / JSIVariableLabel: First Draft Document

Noice! I think I like the look of its capabilities. Quick question, would it be necessary to learn lua programming in order to use RPM2 effectively. Also, what do you think of my JSIEngine idea above?

**Comment by MOARdV** [comment]
>Noice! I think I like the look of its capabilities. Quick question, would it be necessary to learn lua programming in order to use RPM2 effectively.

To get the most out of it, a little bit of Lua would be helpful.  You don't need much of it - enough to know how to write if / then statements, and simple maths.  And that's only if you want to do something fancy.

>Also, what do you think of my JSIEngine idea above?

The main issue is that prefixing it with a variable that's already defined (THRUST and THRUST_#) adds some complexity when parsing the variable.  That, and it requires additional data processing (in addition to the global / total values, I have to track each group, as well).

That said, I think something like that definitely makes sense for an approach.  I would probably go an additional step and make engines default to Group 0, and the player can opt engines in to other groups in the VAB/SPH.  I don't know if I am going to add it in to RPM soon - it would be much easier to design it in from the start (that is, for RPM2 / MAS).
