### ISSUE TITLE
Part Status?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#443]
I assume that your aware that parts have a status. Different parts can have different status.
E.g. Engine can be Nominal, Off, Flame Out.

I was wondering if there would be someway of tracking that. 
Maybe something like, show light when landing gear is moving then show another light when landing gear is down.
You also have 'Broken' status for some wheels, landing legs and solar panels.

There are some parts though that don't display their status, I was wondering if they still have one?
This would also link nicely with #304

**Comment by MOARdV** [comment]
I'm still working out the individual part identifiers - in particular, what is the best way to route a query (how does RPM know which engine you're asking about, for instance).  I need to solve that before I can do something like this with any per-part specificity.

Landing gear has a status value (assuming it works) that I can read to see "deploying", "retracting", etc.

As for the other status items - if it's something that shows up in-game (such as with solar panels, wheels, etc), I can add that status at some point.  If it's not something that has game-play value (other parts), I won't (no sense making up status information if it has no bearing on the game).

**Comment by DeputyLOL** [comment]
What about mods?
I ask this as I'm using adjustable landing gear mod.
It doesn't display its status on the right click menu.
Would there still be a way of tracking

**Comment by DeputyLOL** [comment]
Also, what If you do what you did with the external cameras?
In the VAB/SPH, you place the part then assign it an ID?

Or do you want it to be automatic?
If so, then why not have a pre set 'code' of how rpm looks for things?
My idea would be sorting by parts (Engine, wheels)
Then assigning a number based on part type (Wheezy Engine = 1/ Whiplash = 2/...)
Then putting a number on the end of that to separate 2 of the same type of engine.
E.g.
ENG_1_0 would be a wheezy engine.
ENG_1_1 would be a second wheezy engine.
LGEAR_1_0 could be some sort of landing gear.
OTHER_ would be used for things that cant really be listed (such as mod items)

That's my idea, I just wanted to put it out there. I'm not asking it to be like this I'm just trying to throw some ideas out even though I know nothing about coding. :D

**Comment by MOARdV** [comment]
> What about mods?

That will depend on the mod.  If it is not using a stock module, then I'd have to write code specifically to interface with it (like I do for RealChute, etc).

> Also, what If you do what you did with the external cameras?

I will have to do something like that - I plan on having a JSIEngineControl mod, for instance, that will provide more control of engines.  I don't want to force that onto every part, however, because it becomes an absolute mess for the player to manage.  It must be an opt-in feature.  I don't want to add modules to all parts in the game, because it will slow the game down for people who don't use the feature (there is a cost to adding extra modules).

> Or do you want it to be automatic?

No ,,, that would be a nightmare, and it requires me to make numerous assumptions, and it requires that I update all of the number assignments every single time KSP changes something (and have to manage all the modded parts that people will inevitably want supported), and ... well, it's a huge mess, and it's a non-starter.  I don't have enough time to keep something like that maintained if I want to spend any time doing anything else.

**Comment by DeputyLOL** [comment]
ok, have you considered what would happen if a certain part were to 'disappear' mid flight? 
Such as an engine exploding or detaching?

**Comment by DeputyLOL** [comment]
What about the flap movement in FAR, is there anyway to track when the flaps are moving?

**Comment by MOARdV** [comment]
> Such as an engine exploding or detaching? 

The part is no longer part of the vessel, so it's no longer tracked.  I'm not going to add a way to detect when parts are lost, because it requires me keeping track of what parts are on the craft, and checking to see if they're missing each update, which is a lot of overhead.  And even that won't persist between saves, so a missing part won't be "missing" next time the same craft is loaded, because the part won't be there at the beginning.

> What about the flap movement in FAR, is there anyway to track when the flaps are moving?

Based on what's exposed in the FAR interface, no.  It doesn't look like FAR actually tracks the movement - it only tracks whether the flaps are in position 0, 1, 2, or 3, so there's no "flaps moving" variable.

**Comment by DeputyLOL** [comment]
Ok that's what I thought might be the case with FAR.

**Comment by MOARdV** [comment]
I'm closing this issue - engine status is already covered by another open issue, and the complexity of having to track individual parts of multiple types is more coding effort than I can justify.
