### ISSUE TITLE
magical floating external camera view

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#468]
now whille we typically use RPM to get away from Mr magical floating external camera, after seeing some nice documentaries and such using CGI to show path of launch etc, i feel like this would be a valid view for RPM to support, mainly used for IVA of probes i would think but hey

**Comment by MOARdV** [comment]
This functionality already exists.  Edit one of the existing external cameras, or make a new config, and reposition the camera using the `rotateCamera` and `translateCamera` parameters in [JSIExternalCameraSelector](https://github.com/Mihara/RasterPropMonitor/wiki/Part-modules#jsiexternalcameraselector).

I'm not interested in adding any parts to the RPM distribution for this use since it would require user tuning for every ship, and adding controls to do that in-game is well outside the scope of RPM.
