### ISSUE TITLE
Separate JSITransparentPod from RPM

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#476]
JSITransparentPod doesn't really fit with the core RPM behavior, since it's providing an external view of the interior of the vessel.  It'd make more sense to split it into its own feature, so people who don't want RPM-enhanced IVA can still have transparent pods, and vice versa.

@JPLRepo has already taken the first several steps to splitting it into a separate DLL.

**Comment by sumghai** [comment]
Agreed wholeheartedly.

**Comment by JPLRepo** [comment]
I have a working dev stand-alone version already. It has one outstanding issue with the new portrait cam manager to remove portraits for Kerbals that aren't pods in range but not active vessel. Working on that and looking for other performance improvements, but so far fruitless effort. Attempting to do similar to how squad have done the via overlay will not work due to unity camera layer processing. For that to work we would need the IVA layers to render behind the foreground of external models but in front of the rear of same models. Once I get the portrait cams sorted I'll work with MOARdV to post a pre-release version.

**Comment by JPLRepo** [comment]
Update: Thanks to the new DepthMask shader in part tools I have managed to use the same method as Squad for the TransparentPods feature in flight. It has a huge performance gain. For the editor, it's not so easy because parts can be removed, attached, rotated, etc. Trying to do this with one camera is almost impossible. So I have reverted to the OLD method for TransparentPods in the editor which works fine. I still have an issue with portraits appearing for parts that are loaded but not the active vessel. Still need to figure out how to remove them using the new portrait manager system that Squad has introduced in 1.1 (with very little public vars to play with, it may be impossible).
This will require model changes for mods using TransparentPods. In particular, an Overlay mesh must be created that matches the external onto the Internal Model with the new DepthMask shader applied to it. I'll have to write up wiki changes on the requirements.

**Comment by sumghai** [comment]
Thanks for the update, @JPLRepo - much appreciated.

I've pretty much put FusTek Station Parts on the back burner now, at least until I wrap my head properly around KSP 1.1 and the corresponding PartTool's changes, particularly whether they would break existing add-ons.

**Comment by JPLRepo** [comment]
The good news is... In flight I saw HUGE performance gains... hardly any lag at all. The advantage of the new JSIAdvTransparentPods over the Squad IVA OVerlay will be:
They work in the editor.
They can be toggled ON/OFF/Auto (with mouse hover) on each part that has the module.
In flight they are always on (if toggled on) and appear for all loaded vessels, not just the active vessel.
You can still have it do shader swaps for you on transforms if you want (not sure if there is still a use for this).
The new module will detect when you toggle the stock 1.1 IVA Overlay and turn itself off... then back on again when you turn the stock Overlay off.

**Comment by JPLRepo** [comment]
JSIAdvTransparentPods - NB: Two parts at the bottom have the new TransparentPods module assigned to them. The one on the left has an Occlusion Mesh. The one on the right does not... and therefore appears as it would using the stock IVA overlay. Note the FPS is 104.
![Screenshot1](http://i.imgur.com/HOPzSVD.png)   


This is with Stock IVA Overlay ON, so all three parts IVAs are shown. Note the FPS is 100.
![Screenshot2](http://i.imgur.com/7olzojM.png)

**Comment by JPLRepo** [comment]
Basic Overview of how it works (will expand on this a lot more and write it up a lot more for the Wiki update).
![image3](http://i.imgur.com/CwwjqfF.jpg)

**Comment by sumghai** [comment]
> @sumghai - what in particular do you think is broken? So far my parts and mu's work directly from 1.0.5 into 1.1. Of course to do the transparentpods above they need changes.
The new part tools work pretty much the same. There are all new shaders to deal with, but all the old shaders are still supported and available in the new part tools under "legacy"
If you mean other mods like RPM in your configs, then yeah, you will have to follow those up with other mods. But you can just disable them for testing for now.

@JPLRepo - This is probably best discussed elsewhere. I'll shoot you a forums PM.
