### ISSUE TITLE
IVA undocking bug

### ISSUE THREAD

**Issue by aihaw** [Mihara/RasterPropMonitor#524]
Hey! Thanks for this awesome mod. However, using the last version with KSP 1.1.2, when undocking from IVA menus, switching to the other vessel IVA the screens are all buggy. Not a big issue, as undocking from external view makes it work. It is more kind of an immersion breaker...

**Comment by MOARdV** [comment]
I have tried a couple of things to get this working right, and it still isn't.  Undocking really messes things up, and short of going to the space center and returning, I haven't found anything that makes it behave better.

**Comment by Alexustas** [comment]
It seems on the docking / undocking breaking JSICallbackAnimator and RasterPropMonitorComputer modules and storedStrings 

``` 
RPMVesselComputer: Attempt to re-initialize storedStrings with a different values was ignored.


and I also noticed Enable/Disable Engines switch stops reactivate disabled engines

**Comment by Alexustas** [comment]
Here is a latest dev version of my ASET_props, parts and internals
https://www.dropbox.com/s/sqww7r6y70xnvid/ASET_Dev-11-05-2016.zip?dl=0
You can check dock/undock issues

**Comment by MOARdV** [comment]
> and I also noticed Enable/Disable Engines switch stops reactivate disabled engines

KSP changes the stage of the craft when you undock.  So, if the craft was stage 2 when it docked, it is stage 3 when undocked.  You have to manually stage one time after undocking when that happens.

**Comment by Alexustas** [comment]
> KSP changes the stage of the craft when you undock.

Thank you, I did not know that

**Comment by MOARdV** [comment]
> Thank you, I did not know that

I think that is new in KSP 1.1.

**Comment by Alexustas** [comment]
> NullReferenceException: Object reference not set to an instance of an object
>   at JSI.JSITargetMenu.UpdateReferencePartAsClaw () [0x00000] in <filename unknown>:0 

>   at JSI.JSITargetMenu.ShowMenu (Int32 width, Int32 height) [0x00000] in <filename unknown>:0 

>   at JSI.MonitorPage.UpdateText (JSI.RPMVesselComputer comp) [0x00000] in <filename unknown>:0 

>   at JSI.RasterPropMonitor.FillScreenBuffer () [0x00000] in <filename unknown>:0 

>   at JSI.RasterPropMonitor.OnUpdate () [0x00000] in <filename unknown>:0 

>   at InternalProp.OnUpdate () [0x00000] in <filename unknown>:0 

>   at InternalModel.OnUpdate () [0x00000] in <filename unknown>:0 

>   at Part.InternalOnUpdate () [0x00000] in <filename unknown>:0 

>   at Part.Update () [0x00000] in <filename unknown>:0 
 
> (Filename:  Line: -1)

**Comment by MOARdV** [comment]
> sometimes stops working target selection menu

Argh.  Okay.  Undocking works very badly.

**Comment by MOARdV** [comment]
Finally got the storedStrings sorted out.  Poor assumption on my part when I made changes a while ago.

**Comment by MOARdV** [comment]
I've made a few changes.  I think I've fixed the storedStrings bug, and I think the docking / undocking behavior is better (I fixed the JSITargetMenu problem and one in JSILabel).

A dev build is available on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0), if someone else wants to look at it to see if it helps.

**Comment by Alexustas** [comment]
NRE spamming in debug after docking. After switching to KCS and back all work normal

```
NullReferenceException: Object reference not set to an instance of an object
  at JSI.JSIVariableLabel.OnCallback (JSI.RPMVesselComputer comp, Single value) [0x00000] in <filename unknown>:0 

  at JSI.RPMVesselComputer.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

[output.log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

[ASET dev build](https://www.dropbox.com/s/qnoqi8ysraexk2i/ASET_Dev-28-05-2016.zip?dl=0)

**Comment by MOARdV** [comment]
> NRE spamming in debug after docking.

ARgh.  Okay, this callback stuff is a serious nuisance.  I think I missed JSIVariableLabel with the changes I made.

**Comment by MOARdV** [comment]
Updated on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) again.

**Comment by Alexustas** [comment]
RPM 0.26.1.11449
I still have same issue.
Callbackanimator breaks after docking and noticeable lags appeared
[log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

**Comment by MOARdV** [comment]
I wonder if Squad broke something on docking.  Your error log has notices that regular buttons are breaking (ButtonSASModePrograde, for instance).

What pods are you docking?  ALCOR docking to ???  I don't see anything this bad happening with the pod I have been using.

**Comment by MOARdV** [comment]
DLL only update [DropBox](https://www.dropbox.com/s/colgs7nml0cujwn/RasterPropMonitor-dev.0.26.1-dll.zip?dl=0).  This fixes the richText not updating correctly, and it adds null checks to the JSIInternalRPMButtons methods that did not already have them.

I am still trying to understand the problem with the callbacks.

**Comment by Alexustas** [comment]
> What pods are you docking? ALCOR docking to ??? 

Yes, I'm docking ALCOR and MK1-2 (with my custom IVA)

**Comment by Alexustas** [comment]
No chages ((

[log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

[ASET stuff](https://www.dropbox.com/s/fmchad75s77vemz/ASET_Dev-29-05-2016.zip?dl=0)

**Comment by MOARdV** [comment]
What a mess...

When two vessels are docked, I see the props register callbacks like they should with the one Vessel that exists (call if Vessel A).  Everything is okay.

When the vessel undock, KSP creates a new vessel (call it Vessel B).  The props on Vessel A that are going to belong to Vessel B are destroyed, since new props are going to be created for Vessel B.

But ... When the OnDestroy method is called for those props, it already has Vessel B's ID, so it tried to remove itself from Vessel B's callback list, which is empty.

Then, Vessel A calls its callbacks, since we just undocked.  All of the Vessel B props that were destroyed are still in the Vessel A callback list, so their callback method is called.  They see that the vessel that is updating them is not the same vessel as the one they belong to (Vessel A is updating them, but KSP already put them on Vessel B), so they unregister with Vessel A.

Why, Squad, did you move those props to a new Vessel before destroying them?

I think can store the GUID of the vessel the props register with, and use that for unregistering, but that seems awfully messy.  I don't see a cleaner way to handle this.

And so far all of this has been docking Mk1-2 to ALCOR (flying Mk1-2), so I don't get kicked out of IVA because my craft "disappears".  I haven't tried flying the ALCOR into the Mk1-2 yet.

**Comment by MOARdV** [comment]
Latest iteration of the "maybe fix" on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) - this is a full ZIP package.

**Comment by Alexustas** [comment]
>  "maybe fix" 

no. same issue (((

I also noticed that after docking breaks control of ALCOR's built in lighting. I turned on the docking spotlight during docking and now after docking can not turn it off.

**Comment by MOARdV** [comment]
> no. same issue (((

Hmm.  Can you put craft files on DropBox?  Maybe if I try with exactly the same craft, I can see the same problem.

**Comment by Alexustas** [comment]
I forgot to specify. my current version of RPM is 0.26.1.17770

**Comment by Alexustas** [comment]
> Can you put craft files on DropBox?

I used KWRocketry parts. so maybe I should make a new mission using only stock parts

**Comment by Alexustas** [comment]
>Can you put craft files on DropBox?

Ok. [ASET props and test craft ](https://www.dropbox.com/s/o2h23kr8cbkmjf4/ASET_Dev-31-05-2016.zip?dl=0)


![screenshot156](https://cloud.githubusercontent.com/assets/6713671/15659439/542bd1d6-26ec-11e6-9331-c7d4d9bd47d3.png)


a very strange thing...

 I did two launches:

1. After separation ALCOR and Orbiter I docked them back controlling from ALCOR. after docking ALCOR is broken as before.

2. After separation ALCOR and Orbiter I docked them back controlling from the Orbiter. after docking everything works fine.

**Comment by MOARdV** [comment]
> a very strange thing...

This is good to know.  I launched as two separate craft, and I did rendezvous in orbit.  I did not think about launching as one craft, which is a stupid oversight if I look at historical moon missions. ))  It may help narrow down the problem.

**Comment by Alexustas** [comment]
>  I did not think about launching as one craft

we must check wide range of options and combinations

**Comment by MOARdV** [comment]
Arg.  Docking ALCOR to Mk1-2 (flying ALCOR), the button module that was created for the ALCOR craft is still used after docking, even though the craft it was on no longer exists (although I never see the VesselModule destroyed ?!?).  So now I need to see if there is a new button module created in the new craft as well, or if the old module is still in use.  If it is the latter, I need a way to tell plugins (and the module) what craft it now belongs to.

**Comment by MOARdV** [comment]
I have torn the variable processing and callback system apart and re-attached it to part modules instead of the vessel module.  This *should* make it more reliable for most situations, although there is still a lot of work I need to do to migrate the rest of the variables back up to the part module.

However...

There is still something going on with the internal cockpit lights (`TurnInternalCockpitLights`) and flood lights (`FloodLights`) in the IVA after undocking.  I am still collecting info on it.

Also, repeated docking/undocking in the same flight (dock ALCOR to Mk1-2, and then undock again) still behaves badly last time I checked it.  Unloading / reloading the craft seems to fix it (eg, go to space center, go to a different craft outside of physics range).  I may have improved the behavior, but I have not re-retested it, since I am still trying to understand the cockpit lights problem.

**Comment by MOARdV** [comment]
Found the cockpit lights problem.  The props were querying if SYSR_ELECTRICCHARGE was available before the vessel computer had updated resource values, so they were being told "No, no power".  I was able to get an update check placed right when switching to the craft, so that problem should be solved.  At last.

**Comment by MOARdV** [comment]
Updated on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  I have not tested docking / undocking more than once between visits to the space center (I have not had time), but I think the behavior may be better.

This will slightly break existing saves - all persistent variables will be reset.

**Comment by Alexustas** [comment]
after undocking via ALCOR MFD I was automatically switched to MK1-2. MK1-2 worked fine it is not broke. I switched to ALCOR and saw that it was broken. SAS mode buttons  and SRC, as well as "Clear target" and maybe something else stop working, and debug starts to spamming error messages.
switching to KSC and back do not fix ALCOR IVA

RPM 0.26.1.20382

[ksp.log](https://www.dropbox.com/s/z7wu9fz42j7z2jv/KSP.log?dl=0)
[output.log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)
latest [ASET stuff](https://www.dropbox.com/s/w8u0azkht22evon/ASET_Dev-04-05-2016.zip?dl=0)

**Comment by Alexustas** [comment]
I forgot to mention an important point. 
_before_ undocking was performed docking. And after docking both IVA worked fine. then I did undocking described above

**Comment by MOARdV** [comment]
This is a big mess...  I now understand what was happening, and I think it works now, EXCEPT: after undocking, when you leave and return, once of the vessels will forget all of its persistent values.  I am still trying to fix that.

Update on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by MOARdV** [comment]
Even with this change, there is a bad bug happening.  If I do too many docks and undocks, all vessels are lost in the persistent file.  I believe this is a KSP bug - I do not know how RasterPropMonitor could erase all vessels.

**Comment by Alexustas** [comment]
1. I made a separation of the ships after reaching orbit. Both IVAs worked fine 
2. I docked ALСOR  to the Orbiter. everything still worked fine
3. I undock ships? using Orbiters MFD. everything worked fine
4. once again I docked ships from Orbiter IVA . very noticeable lags appeared. 
everything still worked fine. except that "CLEAR TARGET" function is still active

Then I switched to the KSC and switched to the tracking station. and then there was a glitch. the list of ships was empty

RPM 0.26.1.21783

[ksp.log](https://www.dropbox.com/s/z7wu9fz42j7z2jv/KSP.log?dl=0)
[output.log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

**Comment by MOARdV** [comment]
> Then I switched to the KSC and switched to the tracking station. and then there was a glitch. the list of ships was empty

I think this is KSP bug.  All ships are missing from persistents file.

**Comment by MOARdV** [comment]
Ugh.  More testing...  All of the changes I made to fix the undocking problem cause lag in the ALCOR capsule.  And there is still an undocking problem.

**Comment by MOARdV** [comment]
Okay.  I *think* I solved the "All vessels disappeared" problem.  Another assumption I had in VesselModule behavior was incorrect.  I do not see the vessels disappearing now.

@Alexustas  - when you have time, can you please confirm with the new drop on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0)?

**Comment by Alexustas** [comment]
so. I repeated the previous mission.
after the separation I made a 4 "undocking-docking" cycles . everything works fine, the ships do not disappear after switching to KSC and Trackig station

[KSP.log](https://www.dropbox.com/s/z7wu9fz42j7z2jv/KSP.log?dl=0)
[output.log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

**Comment by Alexustas** [comment]
and I noticed such a thing.
same persisetents in the docked  capsules are now (?) independent. eg "ALTITUDE WARNING" in ALCOR I set to "450", in Orbiter  - "750".  I disabled AVAS and GPVS in  ALCOR, but they are still enabled in Orbiter.

Previously it worked exactly the same way? I have just noticed it?

**Comment by Alexustas** [comment]
RPM 0.26.1.20470

**Comment by MOARdV** [comment]
> Previously it worked exactly the same way? I have just noticed it?

No, that was one of the many changes I made to fix this bug.  Each part now has separate persistent variables, so that if a craft undocks, it does not forget all of the variables, and when two craft dock, I do not have to guess which persistent variable is correct (such as if AVAS is on in the orbiter, and off in the ALCOR, what is the correct value when they are docked?).

If we need shared variables (so all docked craft get the same variable), I think I can make that work as a special type of persistent variable, but it still has the problem of "what happens when two craft dock, and they do not have the same value?".
