### ISSUE TITLE
Ignore This

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#566]
Accidently posted something and now I wish I could delete it...

**Comment by MOARdV** [comment]
Not a problem.  Although, to answer your question, JSICallbackAnimator detects changes as soon as RasterPropMonitorComputer updates variables.  How frequently RPMC updates variables is presently a function of the minimum `refreshRate` in all of the props installed in the IVA.  The advantage to JSICallbackAnimator to JSIVariableAnimator is this:

For every Update (which is something like every screen refresh), each JSIVA will ask itself if it's time to refresh.  Every `refreshRate` number of updates, when it is time to refresh, it will check its variable and the range it's in.  If the variable has changed, it will then update its animations.

With JSICA, the props are not called on Update.  Instead, every RPMC `refreshRate` update, RPMC will check every subscribed variable, and it will notify all the subscribers if there is a change.  Otherwise the subscribers are left alone, and they don't contribute any processing overhead.

One advantage to JSICA is that as soon as the variable officially updates in RPMC, every subscriber is told.  With JSIVA, the prop will not see the change until its own update, which is why you would see a delay between different props lighting up when turning on instrument lighting.

Another is computational cost - every JSIVariableAnimator is called on Update, which adds up to hundreds of calls in a complex IVA.  And when they query variables every single one of them checks what the variable's value is, determines where it falls in the range, and decides if that new variable warrants updating animations - which, again in the instrument lighting case, amounted to hundreds of props asking "What is the back light persistent's setting?"  and then doing some math to scale that value before saying "is this different than it was?"..

To actually address the question - JSICallbackAnimator is as likely to catch quick changing variables as JSIVariableAnimator with `refreshRate = 1`.  However, JSICallbackAnimator is less computationally expensive, because only one entity queries the value and determines if it changed, where in JSIVariableAnimator, every single entity queries the value and determines if it changed.

I plan on making changes to JSIVariableAnimator to make it less expensive, since it is crucial for non-threshold animations (like flap indicators, heading indicators, etc).

**Comment by DeputyLOL** [comment]
Yeah, I thought so. I'm moving all my altitude callouts to callback animator to save on overheads and because when descending too fast, variable animator usually missed the callout. Thanks.
