### ISSUE TITLE
MechJeb integration broken and thus malfunctions in RPM and the ASET Props

### ISSUE THREAD

**Issue by Neo2323** [Mihara/RasterPropMonitor#650]
Specs:
Windows 7 - 64bit
KSP: 1.3.1
RPM: 0.29.2

Hi, i really like playing in IVA and though love RPM and the ASET props. After updating everything to the latest versions, I discovered this incompatibility.
The latest dev versions of MechJeb2 are no longer recognized in RPM. Testet with MechJeb 2.6.1.0 build 761 and some older versions before that. The RPM MJ page shows no MechJeb module installed, even though it is installed. Because of that, all ASET prop IVA features for MechJeb do not function too.
With a way older version of MechJeb, RPM detects it and it works as usual, and the ASET props are working too.
Hope this can be fixed. Even though I use MJ mostly for the info windows, the older versions are really buggy in KSP 1.3.1 and I would prefer the recent dev versions to function with RPM.
Link to the MJ dev version I use: https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/
Other Mods installed: Not much, just updating all my IVAs to ASET 1.5 for now.
Thanks.

P.S. Sorry for my english.

**Comment by MOARdV** [comment]
Last time I checked, RPM works correctly with the last released version of MechJeb.

I do not want to update RPM to support a dev version, since dev versions change often.  It could be possible that another dev update would once again cause RPM to stop working, and then I have to make changes again.  When sarbian releases a new official MechJeb release, I will update RPM to work with it if that is needed.

**Comment by brianmcnett** [comment]
If you want to maintain compatibility with the dev builds of MechJeb,
sarbian and his crew do also use Github and they've proven to be remarkably
open to discussing integration issues. It's a daunting thing, however, and
the dev builds of MechJeb are nigh-impossible to keep up with. Unless
there's some other feature or bug-fix in your way, you may have to roll
back temporarily. Bleeding-edge issues.

--b

**Comment by MOARdV** [comment]
> If you want to maintain compatibility with the dev builds of MechJeb,

I've worked with sarbian before.  However, I'm not willing to chase changes caused by dev builds that require re-releasing the mod, particularly since dev builds are a moving target.  Once MJ settles down for an official release, I'll take care of the changes required.  Until then, as you say, bleeding-edge issues.
