### ISSUE TITLE
Small issues with the camera part (mass, texture)

### ISSUE THREAD

**Issue by Corax** [Mihara/RasterPropMonitor#661]
Would it be possible to change the camera's mass in one of the next updates?

It's certainly not a pressing issue, but according to KIS (and eyesight), the external camera has a volume of about 1750 cm³, or just under 2 litres, yet it has a mass of 40 kg - about the density of solid platinum. It's enough to significantly shift the centre of mass on smaller vessels.
My guess would be it's off by a factor of ten.

Also I seem to remember that the camera texture once had an indicator (blue line on top?) helping with orienting it right-side-up; that seems to have gone missing. If I mis-remembered, then I'd make this a feature request instead.

TIA

https://github.com/Mihara/RasterPropMonitor/blob/d7dde441a0f83669d45993b74bb1039482c75d14/GameData/JSI/RasterPropMonitor/Library/Parts/ExternalCameraPart/external-camera.cfg#L35

- -mass = 0.04
+ +mass = 0.004

**Comment by MOARdV** [comment]
The mass is a trivial fix, and I'll include it in the next update.  The texture has not been updated since Mihara made it, as far as I know, I took a look at the texture, and there didn't appear to be any intentional stripes added to it.  If I have some spare time, I can look into tweaking it, but no guarantee on that.

**Comment by MOARdV** [comment]
This is fixed, and it'll be in the RPM update (whenever I get around to releasing one :( )
